# Generated by Django 2.2.10 on 2021-04-23 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorySession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('advisor_name', models.CharField(blank=True, max_length=150)),
                ('place', models.CharField(blank=True, max_length=150)),
                ('overview', models.TextField(blank=True)),
                ('details', models.TextField(blank=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdvisorySessionSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('summary_text', models.TextField(blank=True)),
                ('protocol_text', models.TextField(blank=True)),
                ('created_by', models.CharField(max_length=150)),
                ('modified_by', models.CharField(blank=True, max_length=150)),
                ('evt_created', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('evt_modified', models.DateTimeField(auto_now=True, verbose_name='Modified on')),
                ('advisory_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AdvisorySession')),
            ],
        ),
    ]
