# Generated by Django 2.2.10 on 2021-04-28 06:17

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_persontest_bodyupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisorysession',
            name='created_by',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advisorysession',
            name='evt_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advisorysession',
            name='evt_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified on'),
        ),
        migrations.AddField(
            model_name='advisorysession',
            name='modified_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='advisorysession',
            name='protocol',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advisorysession',
            name='summary',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
