# Generated by Django 2.2.10 on 2021-04-28 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210428_0817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advisorysession',
            old_name='details',
            new_name='hot_leads',
        ),
    ]
