# Generated by Django 2.2.10 on 2021-04-28 11:27

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210428_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisorysession',
            name='type',
            field=models.CharField(choices=[('advisory', 'advisory'), ('next-advisory', 'next-advisory'), ('event', 'event')], max_length=150),
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('reminder_date', models.DateTimeField(null=True, verbose_name='Date')),
                ('evt_created', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('evt_modified', models.DateTimeField(auto_now=True, verbose_name='Modified on')),
                ('advisory_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.AdvisorySession')),
            ],
        ),
    ]
