# Generated by Django 2.2.10 on 2021-04-30 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210429_1146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdvisorySessionSummary',
        ),
    ]
