# Generated by Django 2.2.10 on 2021-04-30 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_delete_advisorysessionsummary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonTest',
        ),
    ]
