# Generated by Django 2.2.10 on 2021-05-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210504_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='evt_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Verändert am'),
        ),
    ]
