# Generated by Django 2.2.10 on 2021-05-04 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210504_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='advisory_session',
        ),
    ]
