# Generated by Django 2.2.10 on 2021-05-04 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_notes_advisory_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='advisory_session',
            field=models.ForeignKey(blank=True, db_column='Beratung', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.AdvisorySession'),
        ),
    ]
