# Generated by Django 2.2.10 on 2021-05-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20210504_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Zu erledigen bis'),
        ),
    ]
