# Generated by Django 2.2.10 on 2021-05-06 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20210506_1003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advisorysession',
            old_name='advisor_id',
            new_name='advisor',
        ),
    ]
