# Generated by Django 2.2.10 on 2021-05-18 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisorysession',
            name='investment_details',
        ),
    ]
